### ISSUE TITLE
Heyawake - Drag and Drop does not work on clued cells

### ISSUE THREAD

**Issue by RedStorm1024** [bay73/puzzleduel#89]
On Heyawake puzzles, if a cell has a number in it, then you can't use drag and drop to copy the contents of another cell into it.

It is likely that heyawake shares some code with similar genres (Nurikabe, Tapa...) where the same behavior is desirable because you don't want to accidentally add an X mark to a clued cell since the rules of those genres force them to be unshaded anyways.

**Comment by bay73** [comment]
Thank you. This should be fixed now.
